### PR TITLE
fix max retries error because it's frustrating

### PR DESCRIPTION
**Pull request by to-json**
This is honestly not the best way to do this, the max retries constant is weird and inconsistent with the rest of the file

however, i needed it to work, so, here

### CODE REVIEW

**Comment by vysakh0** [comment]
@to-json thanks for the PR. I had the fix in `dev` branch, hadn't merged and didn't update the version. 

I will update the main branch and publish a new version.

**Comment by vysakh0** [comment]
@to-json can you update to the latest version `0.14.0` there are much more significant improvements. Also curious, which coding framework you're using for this error thing?

**Comment by to-json** [comment]
it was just coming up regularly in attempting to use `drd` at all, but, your new version seems improved, i'll try it

**Comment by to-json** [comment]
sick yeah this covers it. DRD has been fun to play with; i have yet to have it successfully make working software, but it's a cool way to explore what claude can do

thank you

**Pull request closed without merging**
